name: testes

on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: openjdk:11
    services:
      postgres: 
        image: postgres
        ports:
          - 5432:5432
        env: 
         POSTGRES_PASSSWORD: postgres
      redis:
        image: redis:alpine
        ports:
         - 6379:6379
        options: --entrypoint redis-server
    env:
      REDIS_HOST: redis
    steps:
      - uses: actions/checkout@v2
      
#       - name: build JDK11
#         uses: actions/setup-java@v2
#         with: 
#           java-version: '11'
#           distribution: 'adopt'
          
      - name: run tests
        run: chmod +x mvnw && ./mvnw test
